openapi: 3.0.3
info:
  title: flask-apscheduler-test
  version: 2.0.0
servers:
- url: "{protocol}://0.0.0.0:{port}"
  variables:
    protocol:
      enum:
      - http
      - https
      default: http
    port:
      enum:
      - "8000"
      default: "8000"
tags:
- name: scheduler
  description: 调度器相关
- name: job
  description: 作业相关
paths: 
  /custom/scheduler/pause:
    post:
      tags:
      - scheduler
      summary: 暂停调度器
      description: 暂停调度器
      operationId: postSchedulerPause
      requestBody:
        $ref: '#/components/requestBodies/post-scheduler-pause'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'
  /custom/scheduler/resume:
    post:
      tags:
      - scheduler
      summary: 恢复调度器
      description: 恢复调度器
      operationId: postSchedulerResume
      requestBody:
        $ref: '#/components/requestBodies/post-scheduler-resume'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'

  /custom/scheduler/jobs:
    post:
      tags:
      - job
      summary: 添加作业
      description: 添加作业
      operationId: postJobs
      requestBody:
        $ref: '#/components/requestBodies/post-jobs'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'

  /custom/scheduler/jobs/{job_id}/remove:
    post:
      tags:
      - job
      summary: 删除作业
      description: 删除作业
      operationId: postJobsRemove
      parameters:
        - in: path
          name: job_id
          description: 任务ID
          required: true
          schema:
            type: string
            example: 'job1'
      requestBody:
        $ref: '#/components/requestBodies/post-jobs-remove'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'
  /custom/scheduler/jobs/{job_id}:
    patch:
      tags:
      - job
      summary: 更新作业
      description: 更新作业
      operationId: patchJobs
      parameters:
        - in: path
          name: job_id
          description: 任务ID
          required: true
          schema:
            type: string
            example: 'job1'
      requestBody:
        $ref: '#/components/requestBodies/patch-jobs'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'
  /custom/scheduler/jobs/{job_id}/pause:
    post:
      tags:
      - job
      summary: 暂停某个作业
      description: 暂停某个作业
      operationId: postJobsPause
      parameters:
        - in: path
          name: job_id
          description: 任务ID
          required: true
          schema:
            type: string
            example: 'job1'
      requestBody:
        $ref: '#/components/requestBodies/post-jobs-pause'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'
  /custom/scheduler/jobs/{job_id}/resume:
    post:
      tags:
      - job
      summary: 恢复某个作业
      description: 恢复某个作业
      operationId: postJobsResume
      parameters:
        - in: path
          name: job_id
          description: 任务ID
          required: true
          schema:
            type: string
            example: 'job1'
      requestBody:
        $ref: '#/components/requestBodies/post-jobs-resume'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'
  /custom/scheduler/jobs/{job_id}/run:
    post:
      tags:
      - job
      summary: 执行某个作业
      description: 执行某个作业
      operationId: postJobsRun
      parameters:
        - in: path
          name: job_id
          description: 任务ID
          required: true
          schema:
            type: string
            example: 'job1'
      requestBody:
        $ref: '#/components/requestBodies/post-jobs-run'
      responses:
        "200":
          description: 成功响应请求
          content:
            application/json:
              schema:
                $ref: '#/components/responses/general'
              examples:
                "200":
                  $ref: '#/components/examples/general-200'
                "500":
                  $ref: '#/components/examples/general-500'

components:
  schemas:
    post-scheduler-requestbody:
      required:
        - log
      type: object
      properties:
        log:
          type: object
          required:
            - "appId"
            - "entryId"
            - "dataId"
          properties:
            appId:
              type: string
              description: 应用ID
            entryId:
              type: string
              description: 表单ID
            dataId:
              type: string
              description: 数据ID
    post-jobs-requestbody:
      required:
        - log
        - job
      type: object
      properties:
        log:
          type: object
          required:
            - "appId"
            - "entryId"
            - "dataId"
          properties:
            appId:
              type: string
              description: 应用ID
            entryId:
              type: string
              description: 表单ID
            dataId:
              type: string
              description: 数据ID
        job:
          type: object
          required:
            - "id"
            - "func"
            - "args"
            - "trigger"
          properties:
            id:
              type: string
              description: 作业ID
            func:
              type: string
              description: 作业函数
            args:
              type: array
              description: 参数列表
              items: 
                anyOf:
                  - type: number
                  - type: string
            trigger:
              type: string
              description: 触发方式
    patch-jobs-requestbody:
      required:
        - log
        - job
      type: object
      properties:
        log:
          type: object
          required:
            - "appId"
            - "entryId"
            - "dataId"
          properties:
            appId:
              type: string
              description: 应用ID
            entryId:
              type: string
              description: 表单ID
            dataId:
              type: string
              description: 数据ID
        job:
          type: object
          required:
            - "func"
            - "args"
            - "trigger"
          properties:
            func:
              type: string
              description: 作业函数
            args:
              type: array
              description: 参数列表
              items: 
                anyOf:
                  - type: number
                  - type: string
            trigger:
              type: string
              description: 触发方式
    jobs-requestbody:
      required:
        - log
      type: object
      properties:
        log:
          type: object
          required:
            - "appId"
            - "entryId"
            - "dataId"
          properties:
            appId:
              type: string
              description: 应用ID
            entryId:
              type: string
              description: 表单ID
            dataId:
              type: string
              description: 数据ID
    general-response:
      required:
      - code
      - data
      - message
      - success
      type: object
      properties:
        success:
          type: boolean
        code:
          type: integer
        message:
          type: string
        data: {}
      example:
        code: 0
        data:
          loginState: loginState
          phone: phone
        success: true
        message: message
  responses:
    general:
      description: 成功响应请求
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/general-response'
          examples:
            "200":
              $ref: '#/components/examples/general-200'
            "500":
              $ref: '#/components/examples/general-500'
  examples:
    post-scheduler-requestbody:
      description: 请求体
      value:
        log:
          appId: 5b8e39ba111dc526a9845b39
          entryId: 6358e2ac26d2d8000a641352
          dataId: b310a9f0dc8146df9723b226fa9a2b2d
    general-200:
      description: 成功
      value:
        code: 200
        success: true
        data: {}
        message: ''
    general-500:
      description: 成功
      value:
        code: 500
        success: false
        data: {}
        message: ''
    post-jobs-requestbody:
      description: 请求体
      value:
        log:
          appId: 5b8e39ba111dc526a9845b39
          entryId: 6358e2ac26d2d8000a641352
          dataId: b310a9f0dc8146df9723b226fa9a2b2d
        job:
          id: job1
          func: module.test:task
          args: [1, 2]
          trigger: "interval"
          seconds: 10
    jobs-requestbody:
      description: 请求体
      value:
        log:
          appId: 5b8e39ba111dc526a9845b39
          entryId: 6358e2ac26d2d8000a641352
          dataId: b310a9f0dc8146df9723b226fa9a2b2d
    patch-jobs-requestbody:
      description: 请求体
      value:
        log:
          appId: 5b8e39ba111dc526a9845b39
          entryId: 6358e2ac26d2d8000a641352
          dataId: b310a9f0dc8146df9723b226fa9a2b2d
        job:
          func: module.test:task
          args: [1, 2]
          trigger: "interval"
          seconds: 10
  requestBodies:
    post-scheduler-pause:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/post-scheduler-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/post-scheduler-requestbody'
    post-scheduler-resume:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/post-scheduler-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/post-scheduler-requestbody'
    post-jobs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/post-jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/post-jobs-requestbody'
    post-jobs-remove:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/jobs-requestbody'
    patch-jobs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/patch-jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/patch-jobs-requestbody'
    post-jobs-pause:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/jobs-requestbody'
    post-jobs-resume:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/jobs-requestbody'
    post-jobs-run:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/jobs-requestbody'
          examples:
            示例1:
              $ref: '#/components/examples/jobs-requestbody'